mode:
  local:
    # If the notebook is run directly outside a container
    wh_credentials_path: credentials.yaml
  container:
    # If the notebook is run from a container as a sagemaker processing job
    wh_credentials_path: /opt/ml/processing/config/credentials.yaml

data:
  # Ignores any data before this date. If not required, we can give it as None
  min_date: '2022-01-01'

  #Column name where table holds timestamp
  timestamp_column_name: &timestamp_column_name timestamp

  #Primaray key column name
  primary_key_column: &primary_key_column rudder_id

  #Column name of the table where event type is stored
  events_column_name: &events_column_name touch_point 

  #Final columns to be selected
  filter_columns: [*primary_key_column, *events_column_name, *timestamp_column_name]
  
  # Name of the conversion event. this is expected to be one of hte event in events_column_name. Only the events till the first occurence of this are considered and the rest are ignored. 
  conversion_event_name: 'subscription invoice'

  # The input data may sometimes contain a touch that is not required and you choose to drop them. 
  # Such touches should be added to this list. 
  # If all touches should be considered, we can pass an empty list (ex: IGNORE_TOUCHES=[])
  ignore_events: []
  
  # Only the top events (by volume) are considered and rest all are grouped as 'others'. If 'others' is one of the top events already, a suffix is added with current timestamp in epoch
  # (ex: 'others_1657781887'). If all events should be considered, mark this value as null
  n_top_events: 14 # null if all events to be considered
  
  # We may want to combine a few touches into one group. Ex: all video ads from different sources may be combined into one.
  # In such case, we make below flag True (else, False) and create a touchpoint_mapping dictionary (see below) to group related touch points together
  group_events: False
  
  # This is required only if GROUP_TOUCHES: True. In below mapping, each key corresponds to a touch we want to group. 
  # Ex, sources, directory, home etc are all converted to 'webapp' and video-library, guides, case-studies are converted to 'docs'
  # If a touch is not found in the key, no modification is applied on that and it stays as is.
  group_events_mapping: null
  
analysis:
  # Dedup logic. IF same event repeats consecutively within this interval (in seconds), they are considered the same and first occurence timestamp is counted. 
  # If we don't want a dedup logic, we can make this value as 0.
  min_event_interval_in_sec: 300
